export enum REQUEST_NAME {
  UPDATE_USER_STATUS,
  ADD_USER,
  UPDATE_USER,
  DELETE_USER,
  UPDATE_PRODUCT,
}

// Define page id
export enum PAGES {
  BO = 'bo',
  BO_ADMIN = 'bo_admin',
  BO_DOC = 'bo_doc',
  CATEGORIES = 'categories',
  LOGISTIC_FEE = 'logistic_fee',
  ORDERS = 'orders',
  OUTLETS = 'outlets',
  OUTLET_PRODUCT_PRICING = 'oulet_product_pricing',
  PRODUCTS = 'products',
  TAXES = 'taxes',
  USERS = 'users',
  ATTRIBUTES = 'attributes',
  ABANDONED_BASKET = 'abandoned_basket',
  UPSELLS = 'upsells',
  PROMOTIONS = 'promotions',
}

export const PUBLIC_ROUTES = ['/login'];

export const mockFeatures = [
  {
    id: 2,
    name: 'Pack Size',
    description: 'Pack Size',
    value: '',
    featured: true,
    filterable: true,
    position: 7,
    createdOn: '2021-01-13T15:00:49Z',
    updatedOn: '2021-01-13T15:00:49Z',
    __typename: 'DslProductFeature',
  },
  {
    id: 1,
    name: 'SKU Name',
    description: 'SKU Name',
    value: '',
    featured: false,
    filterable: true,
    position: 3,
    createdOn: '2021-01-13T15:00:49Z',
    updatedOn: '2021-01-13T15:00:49Z',
    __typename: 'DslProductFeature',
  },
  {
    id: 3,
    name: 'ABV',
    description: 'ABV',
    value: '',
    featured: true,
    filterable: true,
    position: 8,
    createdOn: '2021-01-13T15:00:49Z',
    updatedOn: '2021-01-13T15:00:49Z',
    __typename: 'DslProductFeature',
  },
  {
    id: 4,
    name: 'Brand Owner',
    description: 'Brand Owner',
    value: '',
    featured: false,
    filterable: true,
    position: 9,
    createdOn: '2021-01-13T15:00:49Z',
    updatedOn: '2021-01-13T15:00:49Z',
    __typename: 'DslProductFeature',
  },
  {
    id: 5,
    name: 'Origin',
    description: 'Origin',
    value: '',
    featured: true,
    filterable: true,
    position: 10,
    createdOn: '2021-01-13T15:00:49Z',
    updatedOn: '2021-01-13T15:00:49Z',
    __typename: 'DslProductFeature',
  },
] as any;
